openapi: 3.0.3
info:
  title: Device Schema
  version: 1.0.0
  description: API for device core schema

components:
  schemas:
    Device:
      title: Device
      description: Device account
      type: object
      properties:
        deviceDisplayName:
          type: string
          description: "Human readable name of the device, suitable for
                        displaying to end-users. For example, 'BLE 
                        Heart Monitor' etc."
          nullable: true
          readOnly: false
          writeOnly: false
        adminState:
          type: boolean
          description: A mutable boolean value indicating the device
                       administrative status. If set TRUE, the commands
                       (such as connect, disconnect, subscribe) that 
                       control app sends to the controller for the 
                       devices will be processeed by the controller. 
                       If set FALSE, any command comming from the 
                       control app for the device will be rejected 
                       by the controller.
          nullable: false
          readOnly: false
          writeOnly: false
        mudUrl:
          type: string
          format: uri
          description: A URL to MUD file of the device (RFC 8520). It
                       is added for future use. Current usage is not 
                       defined yet.
          nullable: true
          readOnly: false
          writeOnly: false
      required:
        - adminState
      additionalProperties: false
      allOf:
        - $ref: '#/components/schemas/CommonAttributes'
    CommonAttributes:
      type: object
      properties:
        id:
          type: string
          format: uri
          description: The unique identifier for a resource.
          nullable: false
          readOnly: true
          writeOnly: false
        externalId:
          type: string
          description: An identifier for the resource that is defined
                       by the provisioning client.
          nullable: true
          readOnly: false
          writeOnly: false
        meta:
          type: object
          properties:
            resourceType:
              type: string
              description: The name of the resource type of the 
                           resource.
              nullable: false
              readOnly: true
              writeOnly: false
            location:
              type: string
              format: uri
              description: The URI of the resource being returned.
              nullable: false
              readOnly: false
              writeOnly: false
            created:
              type: string
              format: date-time
              description: The date and time the resource was added to
                           the service provider.
              nullable: false
              readOnly: true
              writeOnly: false
            lastModified:
              type: string
              format: date-time
              description: The most recent date and time that the 
                           details of this resource were updated at the
                           service provider.
              nullable: false
              readOnly: true
              writeOnly: false
            version:
              type: string
              description: The version of the resource. 
              nullable: true
              readOnly: false
              writeOnly: false
          additionalProperties: false
  

paths:
  /devices:
    post:
      summary: Create a new device
      description: Creates a new device.
      operationId: createDevice
      requestBody:
        description: The device to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: The URI of the newly created device.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'

  /devices/{deviceId}:
    get:
      summary: Get a device by ID
      description: Returns a single device by its ID.
      operationId: getDeviceById
      parameters:
        - name: deviceId
          in: path
          description: The ID of the device to return.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'


