openapi: 3.0.1
info:
  version: 1.0.0
  title: Endpoint Apps Extension
  description: Extension for partner endpoint applications that can
               onboard, control, and communicate with the device.

components:
  schemas:
    endpointApps:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/deviceControl'
          - $ref: '#/components/schemas/dataReceiver'  
      
    deviceControl:
      type: array
      items:
        $ref: '#/components/schemas/deviceControlAttributes'
    
    deviceControlAttributes:
      properties:
        client-tokens:
          type: string
          format: uri
          description: This attribute contains a list of tokens that 
                       the client will used to authenticate itself. 
                       Each token may be a string up to 500
                       octets in length.
          nullable: false
          readOnly: false
          writeOnly: false
        enterpriseEndpoint:
          type: string
          format: uri
          description: The URL of the enterprise endpoint which
                       device control apps uses to reach enterprise
                       network gateway. When enterprise receives the
                       SCIM object from onboarding app, it adds this 
                       attribute to the object and sends back the 
                       object as response back to the onboarding
                       app.
          nullable: false
          readOnly: false
          writeOnly: false
      required:
        - client-tokens
        - enterpriseEndpoint

    dataReceiver:
      type: array
      items:
        $ref: '#/components/schemas/dataReceiverAttributes'

    dataReceiverAttributes:
      properties:
        client-tokens:
          type: string
          format: uri
          description: This attribute contains a list of tokens that 
                       the client will used to authenticate itself. 
                       Each token may be a string up to 500 octets
                       in length.
          nullable: false
          readOnly: false
          writeOnly: false

        enterpriseEndpoint:
          type: string
          format: uri
          description: The URL of the enterprise endpoint which data
                       receiver apps uses to reach enterprise network
                       gateway. When enterprise receives the SCIM
                       object from onboarding app, it adds this
                       attribute to the object and sends back the
                      object as response back to the onboarding app.
          nullable: false
          readOnly: false
          writeOnly: false
paths:
  /endpointApps:
    get:
      summary: Get endpoint apps
      description: Returns all endpoint apps
      operationId: getAllEndpointApps
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/endpointApps'
